doc/Contoso-master/Contoso/Controllers/DepartmentController.cs
using System.Web.Mvc;
using Contoso.Model;
using Contoso.Service;

namespace Contoso.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;
        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }
      
        // GET: Department
        public ActionResult Index()
        {
            var departments = _departmentService.GetAllDepartmentsIncludeCourses();
            return View(departments);
        }

        // GET: Department/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Department/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Department/Create
        [HttpPost, Authorize]
        public ActionResult Create(Department department)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Department/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Department/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Department/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Department/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

doc/Contoso-master/Contoso/Controllers/StudentController.cs
using System;
using System.Web.Mvc;
using Contoso.Model;
using Contoso.Service;
using Contoso.ViewModels;
using PagedList;

namespace Contoso.Controllers
{
    // [ContosoAuthorize(Roles = "Student")]
    public class StudentController : BaseController
    {
        private readonly IStudentService _studentService;

        public StudentController(IStudentService studentService)
        {
            _studentService = studentService;
        }

        // GET: Student
        public ActionResult Index(int? page)
        {
            var pageNumber = (page ?? 1) - 1;
            const int pageSize = 10;
            var students = _studentService.GetAllStudents(page, pageSize, out var totalCount);
            var studentsAsIPagedList = new StaticPagedList<Student>(students, pageNumber + 1, pageSize, totalCount);
            return View(studentsAsIPagedList);
        }

        // GET: Student/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        
        // GET: Student/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Student/Create
        [HttpPost, Authorize]
        public ActionResult Create(RegisterViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // TODO: Add insert logic here
                    var student = new Student
                    {
                        Email = model.Username,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        Password = model.Password,
                        EnrollmentDate = DateTime.Now,
                        State =  model.State
                    };

                    _studentService.CreateStudent(student);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                throw;
            }
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Student/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Student/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Student/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

doc/Contoso-master/Contoso/Views/Shared/ErrorPage.cshtml
@{
    ViewBag.Title = "ErrorPage";
}

<h2>    Error Happened, Please try later some time 
</h2>

doc/Contoso-master/Contoso/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-info ">
    <div class="container">

        @Html.ActionLink("Contoso University", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", null, new {@class = "nav-link"})

                </li>

                <li class="nav-item active">
                    @Html.ActionLink("Students", "Index", "Student", null, new {@class = "nav-link"})

                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Courses", "Index", "Course", null, new {@class = "nav-link"})

                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Departments", "Index", "Department", null, new {@class = "nav-link"})

                </li>
                <li class="nav-item active">
                    @Html.ActionLink("About", "About", "Home", null, new {@class = "nav-link"})

                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Contact", "Contact", "Home", null, new {@class = "nav-link"})
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Contoso University</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>